name = "tauri-update-server"
workers_dev = true
compatibility_date = "2022-03-26"
main = "src/index.ts"

[vars]
GITHUB_ACCOUNT = 'Fantasy-programming'
GITHUB_REPO = 'Onlyrefs'
GITHUB_TOKEN = ''                      # Optional - used with private repos

[build]
command = "npm install && npm run build"
